// Code generated by tygo. DO NOT EDIT.
// Source: internal/templates/bestiary_funcs.go.
// Regenerate with `npm run gen:types`.
import type { RoomSheetKind } from "../room/payload.gen";

//////////
// source: bestiary_funcs.go

/**
 * BestiaryPayload is what the /bestiary page renders from (#bestiary-state,
 * ui/static/js/bestiary/main.tsx); the collections come over HTTP.
 */
export interface BestiaryPayload {
  csrfToken: string;
  sheetKinds: RoomSheetKind[];
}
