// Code generated by tygo. DO NOT EDIT.
// Source: internal/models/bestiary_views.go.
// Regenerate with `npm run gen:types`.
import type { SheetKind } from "../sheet/kinds/kinds.gen";

//////////
// source: bestiary_views.go

/**
 * BestiaryCollection is a collection of the user or a public one of another
 * user.
 */
export interface BestiaryCollection {
  id: number /* int */;
  name: string;
  description: string;
  /**
   * Own is whether the collection is the user's; Owner is its owner's name.
   */
  own: boolean;
  owner: string;
  visibility: 'private' | 'public';
  /**
   * Default is the user's "My creatures": always private, never deleted.
   */
  default: boolean;
  /**
   * Subscribed is whether the user keeps another user's collection in their
   * list.
   */
  subscribed: boolean;
  publishedAt: string | null;
  tags: string[];
  creatures: number /* int */;
  updatedAt: string /* RFC 3339 */;
}
/**
 * CatalogRow is a public collection in the catalog.
 */
export interface CatalogRow {
  id: number /* int */;
  name: string;
  owner: string;
  own: boolean;
  creatures: number /* int */;
  tags: string[];
  publishedAt: string /* RFC 3339 */;
}
/**
 * CatalogPage is a page of the catalog; Next is the cursor of the next page,
 * null on the last.
 */
export interface CatalogPage {
  rows: CatalogRow[];
  next: string | null;
}
/**
 * Creature is a row of the creature table: what it takes to pick one, not
 * the sheet, which comes from /sheet/view/:id.
 */
export interface Creature {
  id: number /* int */;
  collectionId: number /* int */;
  name: string;
  kind: SheetKind;
  tags: string[];
  /**
   * SourceLabel is "collection · author" of another user's creature it was
   * copied from, as they were at the copy.
   */
  sourceLabel: string | null;
  updatedAt: string /* RFC 3339 */;
}
/**
 * Quota is what the NPCs and creatures of the user take, in bytes.
 */
export interface Quota {
  used: number /* int64 */;
  limit: number /* int64 */;
}
/**
 * TagSuggestions are the tags of the user's own and the public collections,
 * the most used first.
 */
export interface TagSuggestions {
  collections: string[];
  creatures: string[];
}
/**
 * Bestiary is what GET /bestiary/collections returns: all the page needs
 * before a collection is picked.
 */
export interface Bestiary {
  collections: BestiaryCollection[];
  quota: Quota;
  tags: TagSuggestions;
}
/**
 * UploadResult is how one uploaded file went.
 */
export interface UploadResult {
  file: string;
  added: number /* int */;
  /**
   * Error is "invalid" or "quota"; empty when the file is in.
   */
  error?: string;
  message?: string;
}
export const CollectionFileFormat = "collection";
export const CollectionFileVersion = 1;
/**
 * CollectionFile is the file of an exported collection; uploading one adds
 * its creatures to a collection.
 */
export interface CollectionFile {
  format: string;
  version: number /* int */;
  name: string;
  description: string;
  tags: string[];
  creatures: CreatureInFile[];
}
/**
 * CreatureInFile is a creature of a collection file; its content is as in
 * the export of a sheet, without the kind inside.
 */
export interface CreatureInFile {
  sheetKind: SheetKind;
  tags: string[];
  content: { [key: string]: unknown };
}
