// Code generated by tygo. DO NOT EDIT.
// Source: internal/models/encounter_views.go.
// Regenerate with `npm run gen:types`.

//////////
// source: encounter_views.go

/**
 * EncounterState is an encounter with its groups and participants. The
 * initiative of a participant is not here: it lives in the participant's sheet.
 */
export interface EncounterState {
  id: number /* int */;
  roomId: number /* int */;
  name: string;
  round: number /* int */;
  /**
   * CurrentGroupID is the group whose turn it is; null before the first
   * "Next" and after a reset.
   */
  currentGroupId: number | null;
  /**
   * Shown is whether the players see this encounter's InitiativeView.
   */
  shown: boolean;
  /**
   * InitiativeView is what the gamemaster's client last published; null
   * before it has.
   */
  initiativeView: InitiativeView | null;
  version: number /* int */;
  updatedAt: string /* RFC 3339 */;
  /**
   * Groups are in turn order: by position, then by the order they were added.
   */
  groups: EncounterGroup[];
  participants: EncounterParticipant[];
}
export interface EncounterGroup {
  id: number /* int */;
  position: number /* int */;
  name: string | null;
}
export interface EncounterParticipant {
  id: number /* int */;
  groupId: number /* int */;
  sheetId: number /* int */;
  /**
   * DisplayName is the name the players see instead of the sheet's.
   */
  displayName: string | null;
  /**
   * NPC is whether the sheet lives in this encounter; otherwise it is a
   * sheet of the room, a character.
   */
  npc: boolean;
  /**
   * Name is the character name of the sheet.
   */
  name: string;
  /**
   * SourceCreatureID is the creature of the NPC's owner the NPC was copied
   * from, next to which "Add variant to bestiary" puts its variant; null for
   * none.
   */
  sourceCreatureId: number | null;
  sourceCreatureName: string | null;
  /**
   * SourceLabel is "collection · author" of the NPC copied from another
   * user's creature; null for a character.
   */
  sourceLabel: string | null;
}
/**
 * EncounterSummary is an encounter in the gamemaster's picker.
 */
export interface EncounterSummary {
  id: number /* int */;
  name: string;
  updatedAt: string /* RFC 3339 */;
}
/**
 * EncounterList is the encounters of a room, the last changed first.
 */
export interface EncounterList {
  encounters: EncounterSummary[];
  shownEncounterId: number | null;
}
/**
 * EncounterLoadResult is how one file of "Load from files…" went.
 */
export interface EncounterLoadResult {
  file: string;
  /**
   * The encounter the file made, its name and how many NPCs it has; unset
   * when it made none.
   */
  encounterId?: number /* int */;
  name?: string;
  npcs: number /* int */;
  /**
   * Error is "invalid" or "quota"; empty when the file is in.
   */
  error?: string;
  message?: string;
}
/**
 * InitiativeView is the turn order the players see: no sheet ids and no
 * wounds, and the names the gamemaster gave for the players.
 */
export interface InitiativeView {
  round: number /* int */;
  /**
   * Current is the index of the row whose turn it is; null for none.
   */
  current: number | null;
  rows: InitiativeRow[];
}
export interface InitiativeRow {
  name: string;
  /**
   * Value is null for a group none of whom has rolled.
   */
  value: number | null;
}
