// Code generated by tygo. DO NOT EDIT.
// Source: internal/models/character_sheets_content.go.
// Regenerate with `npm run gen:types`.

//////////
// source: character_sheets_content.go

export interface CharacterSheetContent {
  characterInfo: CharacterInfo;
  characteristics: { [key: string]: Characteristic};
  conditions: Conditions;
  skillsLeft: { [key: string]: Skill};
  skillsRight: { [key: string]: Skill};
  customSkills: CustomSkills;
  notes: NotesSection;
  infamyPoints: InfamyPoints;
  fatigue: Fatigue;
  resourceTrackers: ResourceTrackers;
  initiative: InitiativeData;
  size: number /* int */;
  movement: Movement;
  armour: Armour;
  powerShields: PowerShields;
  rangedAttacks: RangedAttacks;
  meleeAttacks: MeleeAttacks;
  traits: Traits;
  talents: Talents;
  carryWeightAndEncumbrance: CarryWeightAndEncumbrance;
  gear: Gear;
  cybernetics: Cybernetics;
  experience: Experience;
  mutations: Mutations;
  mentalDisorders: MentalDisorders;
  diseases: Diseases;
  psykana: Psykana;
  technoArcana: TechnoArcana;
}
export interface ItemGrid<T extends any> {
  items: { [key: string]: T};
  layouts: { [key: string]: Position};
}
export interface CharacterInfo {
  characterName: string;
  archetype: string;
  race: string;
  warbandName: string;
  pride: string;
  homeworld: string;
  origin: string;
  gender: string;
  age: string;
  complexion: string;
  disgrace: string;
  motivation: string;
}
export interface Characteristic {
  value: string;
  unnatural?: string;
  tempValue?: string;
  tempUnnatural?: string;
  tempEnabled: boolean;
}
export interface ConditionEntry {
  type: string;
  name: string;
  bonus?: string;
  unnaturalBonus?: string;
  overrideValue?: string;
  overrideUnnatural?: string;
  rollBonus?: string;
  cap?: string;
  skillBonus?: string;
  ablativeWounds?: string;
  initiativeBonus?: string;
  movementBonus?: string;
  apType?: string;
  apValue?: string;
  /**
   * DomainMode limits a roll_bonus entry: "only" the rolls ticked in Domains,
   * all "except" them, or all rolls when empty.
   */
  domainMode?: string;
  domains?: RollDomains;
}
/**
 * RollDomains are the rolls with their own entry point on the sheet, as
 * ROLL_DOMAINS in ui/static/js/sheet/schema/constants.ts lists them.
 */
export interface RollDomains {
  ranged?: boolean;
  melee?: boolean;
  psychic?: boolean;
  techPower?: boolean;
  compensation?: boolean;
}
export interface Condition {
  name: string;
  enabled: boolean;
  stacks: number /* int */;
  entries: ItemGrid<ConditionEntry>;
}
export interface Conditions {
  list: ItemGrid<Condition>;
}
export interface CustomSkills {
  list: ItemGrid<Skill>;
}
export interface Skill {
  name?: string;
  characteristic: string;
  plus0?: boolean;
  plus10?: boolean;
  plus20?: boolean;
  plus30?: boolean;
  miscBonus?: number /* int */;
  difficulty?: number /* int */;
}
export interface NotesSection {
  list: ItemGrid<Note>;
}
export interface Note {
  name: string;
  description: string;
}
export interface InfamyPoints {
  infamyMax: number /* int */;
  infamyCur: number /* int */;
  infamyTemp: number /* int */;
}
export interface Fatigue {
  fatigueMax: number /* int */;
  fatigueCur: number /* int */;
  fatigueMode: string;
}
export interface ResourceTrackers {
  list: ItemGrid<ResourceTracker>;
}
export interface ResourceTracker {
  name: string;
  value: number /* int */;
}
export interface InitiativeData {
  dice: string;
  wsBonus: boolean;
  bsBonus: boolean;
  sBonus: boolean;
  tBonus: boolean;
  aBonus: boolean;
  iBonus: boolean;
  pBonus: boolean;
  wBonus: boolean;
  fBonus: boolean;
  corBonus: boolean;
  infBonus: boolean;
  flatBonus: number /* int */;
  lastInitiative: number /* int */;
}
export interface Movement {
  moveHalf: number /* int */;
  moveFull: number /* int */;
  moveCharge: number /* int */;
  moveRun: number /* int */;
  bonus: number /* int */;
  fullMult: number /* int */;
  chargeMult: number /* int */;
  runMult: number /* int */;
}
export interface Armour {
  head: BodyPart;
  leftArm: BodyPart;
  body: BodyPart;
  rightArm: BodyPart;
  leftLeg: BodyPart;
  rightLeg: BodyPart;
  woundsMax: number /* int */;
  woundsCur: number /* int */;
  toughnessBaseAbsorptionValue: number /* int */;
  naturalArmourValue: number /* int */;
  machineValue: number /* int */;
  daemonicValue: number /* int */;
  otherArmourValue: number /* int */;
}
export interface BodyPart {
  armourValue: number /* int */;
  extra1Name: string;
  extra1Value: number /* int */;
  extra2Name: string;
  extra2Value: number /* int */;
  superArmour: number /* int */;
}
export interface PowerShields {
  list: ItemGrid<PowerShield>;
}
export interface PowerShield {
  name: string;
  rating: string;
  nature: string;
  type: string;
  description: string;
}
export interface RangedAttacks {
  list: ItemGrid<RangedAttack>;
}
export interface RangedAttack {
  name: string;
  class: string;
  range: string;
  damage: string;
  pen: string;
  damageType: string;
  rofSingle: string;
  rofShort: string;
  rofLong: string;
  clipCur: string;
  clipMax: string;
  reload: string;
  special: string;
  upgrades: string;
  description: string;
  roll?: RangedAttackRoll;
  damageMods: ItemGrid<DamageMod>;
}
/**
 * DamageMod is added to the damage of a weapon: an expression as
 * ui/static/js/sheet/damage.ts parses it, e.g. "S.b", "½WS.b▲", "1d10", "-1".
 */
export interface DamageMod {
  expr: string;
  enabled: boolean;
}
export interface MeleeAttacks {
  list: ItemGrid<MeleeAttack>;
}
export interface MeleeAttack {
  name: string;
  group: string;
  grip: string;
  balance: string;
  upgrades: string;
  tabs: ItemGrid<MeleeTab>;
  description: string;
  roll?: MeleeAttackRoll;
  shield?: Shield;
}
export interface MeleeTab {
  profile: string;
  range: string;
  damage: string;
  pen: string;
  damageType: string;
  special: string;
  damageMods: ItemGrid<DamageMod>;
}
export interface Shield {
  subtype: string;
  ap: number /* int */;
  defenseSectors: string;
  arm: string;
  equipped: boolean;
  defensive: boolean;
}
export interface AimColumn {
  selected: string;
  no: number /* int */;
  half: number /* int */;
  full: number /* int */;
}
export interface TargetColumn {
  selected: string;
  no: number /* int */;
  torso: number /* int */;
  leg: number /* int */;
  arm: number /* int */;
  head: number /* int */;
  joint: number /* int */;
  eyes: number /* int */;
}
export interface RangedRangeColumn {
  selected: string;
  melee: number /* int */;
  pointBlank: number /* int */;
  short: number /* int */;
  combat: number /* int */;
  long: number /* int */;
  extreme: number /* int */;
}
export interface RangedRoFColumn {
  selected: string;
  single: number /* int */;
  short: number /* int */;
  long: number /* int */;
  suppression: number /* int */;
}
export interface MeleeBaseColumn {
  selected: string;
  standard: number /* int */;
  charge: number /* int */;
  full: number /* int */;
  careful: number /* int */;
  mounted: number /* int */;
  free: number /* int */;
}
export interface MeleeStanceColumn {
  selected: string;
  standard: number /* int */;
  aggressive: number /* int */;
  defensive: number /* int */;
}
export interface MeleeRoFColumn {
  selected: string;
  single: number /* int */;
  quick: number /* int */;
  lightning: number /* int */;
}
export interface RollExtra {
  enabled: boolean;
  name: string;
  value: number /* int */;
}
export interface RangedAttackRoll {
  aim: AimColumn;
  target: TargetColumn;
  range: RangedRangeColumn;
  rof: RangedRoFColumn;
  extra1: RollExtra;
  extra2: RollExtra;
  baseSelect: string;
}
export interface MeleeAttackRoll {
  aim: AimColumn;
  target: TargetColumn;
  base: MeleeBaseColumn;
  stance: MeleeStanceColumn;
  rof: MeleeRoFColumn;
  extra1: RollExtra;
  extra2: RollExtra;
  baseSelect: string;
}
export interface Traits {
  list: ItemGrid<NamedDescription>;
}
export interface Talents {
  list: ItemGrid<NamedDescription>;
}
export interface NamedDescription {
  name: string;
  description: string;
}
export interface CyberneticImplant {
  name: string;
  description: string;
  entries: ItemGrid<ConditionEntry>;
}
export interface Cybernetics {
  list: ItemGrid<CyberneticImplant>;
}
export interface Gear {
  list: ItemGrid<GearItem>;
}
export interface GearItem {
  name: string;
  weight: number /* float64 */;
  description: string;
  gearType: string;
  carried: boolean;
  equipped: boolean;
  armour?: GearArmour;
  entries: ItemGrid<ConditionEntry>;
}
export interface GearArmourAP {
  head: string;
  torso: string;
  arms: string;
  legs: string;
}
export interface GearArmour {
  ap: GearArmourAP;
  superAp: GearArmourAP;
  special: string;
  upgrades: string;
  ablativeWounds: string;
  strengthBonus: string;
  agilityBonus: string;
  maxAgility: string;
}
export interface CarryWeightAndEncumbrance {
  carryWeightBase: number /* int */;
  encumbrance: number /* float64 */;
  carryWeight: number /* float64 */;
  liftWeight: number /* float64 */;
  pushWeight: number /* float64 */;
}
export interface Experience {
  alignment: string;
  aptitudes: string;
  useAptitudes: boolean;
  useDevotion: boolean;
  experienceTotal: number /* int */;
  experienceSpent: number /* int */;
  experienceRemaining: number /* int */;
  experienceLog: ItemGrid<ExperienceItem>;
}
export interface ExperienceItem {
  name: string;
  experienceCost: number /* int */;
  type?: string;
  level?: number /* int */;
  aptitudes?: string;
  alliedTo?: string;
  hostileTo?: string;
}
export interface Mutations {
  list: ItemGrid<NamedDescription>;
}
export interface MentalDisorders {
  insanityPoints: number /* int */;
  list: ItemGrid<NamedDescription>;
}
export interface Diseases {
  list: ItemGrid<NamedDescription>;
}
export interface PsychicPowersTab {
  name: string;
  powers: ItemGrid<PsychicPower>;
}
export interface Psykana {
  psykanaType: string;
  maxPush: number /* int */;
  basePR: number /* int */;
  sustainedPowers: number /* int */;
  effectivePR: number /* int */;
  testOptions: ItemGrid<TestOption>;
  tabs: ItemGrid<PsychicPowersTab>;
}
/**
 * TestOption is what the powers of a block can be tested on: a
 * characteristic ("W") or a skill ("awareness", "1_common_lore",
 * "custom:<item id>"), and the characteristic the skill is tested on instead
 * of its own. A power's roll refers to it by its id.
 */
export interface TestOption {
  base: string;
  characteristic: string;
}
export interface PsychicPower {
  name: string;
  subtypes: string;
  range: string;
  psychotest: string;
  action: string;
  sustained: string;
  weaponRange: string;
  damage: string;
  pen: string;
  damageType: string;
  rofSingle: string;
  rofShort: string;
  rofLong: string;
  special: string;
  effect: string;
  roll?: PsychicPowerRoll;
}
export interface PsychicPowerRoll {
  /**
   * The id of the option in the block's testOptions the power is tested on.
   */
  testOption: string;
  modifier: number /* int */;
  effectivePR: number /* int */;
  kickPR: number /* int */;
  extra1: RollExtra;
  extra2: RollExtra;
}
export interface TechPowersTab {
  name: string;
  powers: ItemGrid<TechPower>;
}
export interface TechnoArcana {
  currentCognition: number /* int */;
  maxCognition: number /* int */;
  restoreCognition: number /* int */;
  currentEnergy: number /* int */;
  maxEnergy: number /* int */;
  compensationRoll: CompensationRoll;
  testOptions: ItemGrid<TestOption>;
  tabs: ItemGrid<TechPowersTab>;
}
export interface CompensationRoll {
  modifier: number /* int */;
  extra1: RollExtra;
  extra2: RollExtra;
}
export interface TechPower {
  name: string;
  subtypes: string;
  range: string;
  test: string;
  implants: string;
  price: string;
  process: string;
  action: string;
  weaponRange: string;
  damage: string;
  pen: string;
  damageType: string;
  rofSingle: string;
  rofShort: string;
  rofLong: string;
  special: string;
  effect: string;
  roll?: TechPowerRoll;
}
export interface TechPowerRoll {
  testOption: string;
  modifier: number /* int */;
  extra1: RollExtra;
  extra2: RollExtra;
}
export interface Position {
  colIndex: number /* int */;
  rowIndex: number /* int */;
}
