// Code generated by tygo. DO NOT EDIT.
// Source: internal/templates/room_funcs.go.
// Regenerate with `npm run gen:types`.
import type { SheetKind } from "../sheet/kinds/kinds.gen";

//////////
// source: room_funcs.go

/**
 * RoomPayload is what the client renders the room page from: the #room-state
 * script (ui/static/js/room/state.ts). Dates are RFC 3339; the client formats
 * them in the browser's time zone.
 */
export interface RoomPayload {
  roomId: number /* int */;
  /**
   * Players has the current user first.
   */
  players: RoomPlayer[];
  chat: RoomChat;
  dicePresets: RoomDicePreset[];
  commands: RoomCommand[];
  inviteLink: string;
  /**
   * CSRFToken goes with the sheet import form (POST /sheet/import).
   */
  csrfToken: string;
  sheetKinds: RoomSheetKind[];
}
export interface RoomPlayer {
  id: number /* int */;
  name: string;
  role: "gamemaster" | "moderator" | "player";
  joinedAt: string /* RFC 3339 */;
  folders: RoomFolder[];
  sheets: RoomSheet[];
}
export interface RoomFolder {
  id: number /* int */;
  name: string;
  visibility: "everyone_can_edit" | "everyone_can_view" | "everyone_can_see" | "hide_from_players";
  sortOrder: number /* int */;
}
export interface RoomSheet {
  id: number /* int */;
  name: string;
  kind: SheetKind;
  visibility: "everyone_can_edit" | "everyone_can_view" | "everyone_can_see" | "hide_from_players";
  folderId: number | null;
  createdAt: string /* RFC 3339 */;
  updatedAt: string /* RFC 3339 */;
}
/**
 * RoomChat is the newest page of the chat, oldest message first.
 */
export interface RoomChat {
  messages: ChatMessage[];
  hasMore: boolean;
}
export interface ChatMessage {
  id: number /* int */;
  userId: number /* int */;
  userName: string;
  messageBody: string;
  commandResult: string | null;
  characterName: string | null;
  createdAt: string /* RFC 3339 */;
}
export interface RoomDicePreset {
  slot: number /* int */;
  notation: string;
}
export interface RoomCommand {
  command: string;
  description: string;
  detailedDescription: string;
}
export interface RoomSheetKind {
  kind: SheetKind;
  label: string;
}
